CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE library_branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    address VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    normalized_name VARCHAR(150) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(20) UNIQUE,
    title VARCHAR(240) NOT NULL,
    subtitle VARCHAR(240),
    description TEXT,
    language VARCHAR(50) NOT NULL,
    published_year INTEGER,
    publisher VARCHAR(160),
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE book_author (
    book_id BIGINT NOT NULL REFERENCES book(id),
    author_id BIGINT NOT NULL REFERENCES author(id),
    PRIMARY KEY (book_id, author_id)
);

CREATE TABLE book_category (
    book_id BIGINT NOT NULL REFERENCES book(id),
    category_id BIGINT NOT NULL REFERENCES category(id),
    PRIMARY KEY (book_id, category_id)
);

CREATE TABLE book_copy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode VARCHAR(60) NOT NULL UNIQUE,
    accession_number VARCHAR(60) NOT NULL UNIQUE,
    book_id BIGINT NOT NULL REFERENCES book(id),
    branch_id BIGINT NOT NULL REFERENCES library_branch(id),
    shelf_location VARCHAR(80),
    status VARCHAR(30) NOT NULL,
    condition_status VARCHAR(20) NOT NULL,
    acquired_on DATE,
    purchase_price DECIMAL(12,2),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE library_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_number VARCHAR(40) NOT NULL UNIQUE,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(40),
    address VARCHAR(500),
    member_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    joined_on DATE NOT NULL,
    expires_on DATE NOT NULL,
    user_account_id BIGINT UNIQUE REFERENCES app_user(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE circulation_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    default_policy BOOLEAN NOT NULL DEFAULT TRUE,
    loan_period_days INTEGER NOT NULL,
    max_loans INTEGER NOT NULL,
    max_renewals INTEGER NOT NULL,
    grace_period_days INTEGER NOT NULL,
    fine_per_day DECIMAL(12,2) NOT NULL,
    max_fine_per_loan DECIMAL(12,2) NOT NULL,
    block_at_balance DECIMAL(12,2) NOT NULL,
    pickup_days INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE loan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copy_id BIGINT NOT NULL REFERENCES book_copy(id),
    member_id BIGINT NOT NULL REFERENCES library_member(id),
    checked_out_at TIMESTAMP WITH TIME ZONE NOT NULL,
    due_on DATE NOT NULL,
    returned_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL,
    renewal_count INTEGER NOT NULL DEFAULT 0,
    checked_out_by BIGINT NOT NULL REFERENCES app_user(id),
    returned_by BIGINT REFERENCES app_user(id),
    policy_loan_days INTEGER NOT NULL,
    policy_grace_days INTEGER NOT NULL,
    policy_fine_per_day DECIMAL(12,2) NOT NULL,
    policy_max_fine DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id),
    member_id BIGINT NOT NULL REFERENCES library_member(id),
    assigned_copy_id BIGINT REFERENCES book_copy(id),
    status VARCHAR(30) NOT NULL,
    ready_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    fulfilled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE fine_ledger_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES library_member(id),
    loan_id BIGINT REFERENCES loan(id),
    entry_type VARCHAR(30) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    description VARCHAR(500) NOT NULL,
    created_by BIGINT REFERENCES app_user(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE app_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    title VARCHAR(180) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    type VARCHAR(30) NOT NULL,
    read_flag BOOLEAN NOT NULL DEFAULT FALSE,
    dedupe_key VARCHAR(190) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email VARCHAR(190) NOT NULL,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80),
    details VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_book_title ON book(title);
CREATE INDEX idx_copy_book_status ON book_copy(book_id, status);
CREATE INDEX idx_member_name ON library_member(full_name);
CREATE INDEX idx_member_status ON library_member(status);
CREATE INDEX idx_loan_member_status ON loan(member_id, status);
CREATE INDEX idx_loan_due_status ON loan(due_on, status);
CREATE INDEX idx_reservation_book_status ON reservation(book_id, status, created_at);
CREATE INDEX idx_reservation_member_status ON reservation(member_id, status);
CREATE INDEX idx_ledger_member_created ON fine_ledger_entry(member_id, created_at);
CREATE INDEX idx_notification_user_created ON app_notification(user_id, created_at);
CREATE INDEX idx_audit_created ON audit_event(created_at);
